[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.1", default-features = false, features = ["bevy_window", "bevy_winit", "bevy_render", "webgl2", "bevy_asset", "x11"] }

[profile.dev.package."*"]
opt-level = 3
